### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-operator#126]
I ran into the following error when I deployed Kabanero instance configured with a collection repository that is using a self-signed certificate:
```
E0824 02:57:50.135035       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:82
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/signal_unix.go:390
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/collection/resolver.go:32
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:165
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:59
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/kabaneroplatform_controller.go:98
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1258e94]

goroutine 460 [running]:
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1407820, 0x25777e0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/kabanero-io/kabanero-operator/pkg/controller/collection.ResolveIndex(0xc00047ebe0, 0x46, 0x15c2e11, 0x8, 0x12dccfd)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/collection/resolver.go:33 +0x104
github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.featuredCollections(0xc00063d080, 0x8, 0xc000027be8, 0x111bcbe, 0xc000288900, 0x17f5ac0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:165 +0x139
github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.reconcileFeaturedCollections(0x17f5ac0, 0xc000046050, 0xc00063d080, 0x18046c0, 0xc000668ab0, 0xc0006fa4a0, 0x8)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:59 +0x40
github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.(*ReconcileKabanero).Reconcile(0xc0002596e0, 0xc0006fa4a8, 0x8, 0xc0006fa4a0, 0x8, 0x2591f60, 0x3, 0x3, 0x2000000000001)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/kabaneroplatform_controller.go:98 +0x32d
github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000522960, 0x0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007c9e60)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007c9e60, 0x3b9aca00, 0x0, 0x1, 0xc000572300)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007c9e60, 0x3b9aca00, 0xc000572300)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311
```

**Comment by groeges** [comment]
@jgawor Please can you give the steps required to recreate this issue. Thanks.
