### ISSUE TITLE
The kabanero-operator-xxx pod gets into 'error' status in our environment for 3 to 4 times in a day with the logs attached

### ISSUE THREAD

**Issue by aadeshpa** [kabanero-io/kabanero-operator#158]
```
{"level":"info","ts":1567619459.3454823,"logger":"manifestival","msg":"Updating","name":"kabanero/kabanero-cli","type":"apps/v1, Kind=Deployment"}
{"level":"info","ts":1567619460.1452842,"logger":"manifestival","msg":"Updating","name":"kabanero/kabanero-cli","type":"rbac.authorization.k8s.io/v1, Kind=Role"}
{"level":"info","ts":1567619973.7044501,"logger":"controller_kabaneroplatform","msg":"Reconciling Kabanero","Request.Namespace":"kabanero","Request.Name":"kabanero"}
E0904 17:59:43.777279       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:82
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/signal_unix.go:390
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/collection/resolver.go:32
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:165
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:59
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/kabaneroplatform_controller.go:103
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x125f424]

goroutine 506 [running]:
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x144b9a0, 0x2617cb0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/kabanero-io/kabanero-operator/pkg/controller/collection.ResolveIndex(0xc001370060, 0x57, 0x160fe8f, 0x8, 0x131b98a)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/collection/resolver.go:33 +0x104
github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.featuredCollections(0xc000c0c500, 0x8, 0xc00067db60, 0x1121c6e, 0xc00000e008, 0x184c720)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:165 +0x139
github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.reconcileFeaturedCollections(0x184c720, 0xc000042050, 0xc000c0c500, 0x185b5e0, 0xc00070e7b0, 0xc000d65760, 0x8)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/featured_collections.go:59 +0x40
github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.(*ReconcileKabanero).Reconcile(0xc0006b8860, 0xc000d65768, 0x8, 0xc000d65760, 0x8, 0x2632760, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/kabaneroplatform_controller.go:103 +0x33a
github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00031a0a0, 0x0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000599580)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000599580, 0x3b9aca00, 0x0, 0x1, 0xc0004b20c0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000599580, 0x3b9aca00, 0xc0004b20c0)
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/travis/gopath/src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311
```

**Comment by kaczyns** [comment]
We think this was fixed by #142.  Please re-open this issue if you are still experiencing this problem.  Thanks!
