### ISSUE TITLE
Creating Collection in alternate namespace causes crash

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#232]
` oc apply -n coltest -f /tmp/java-mp.yaml`

```
{"level":"info","ts":1570745091.0492072,"logger":"controller_kabaneroplatform","msg":"Reconciling Kabanero","Request.Namespace":"kabanero","Request.Name":"kabanero"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x126e8fe]

goroutine 477 [running]:
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x14c3100, 0x251e5a0)
        /home/dacleyra/go-build/goroot/src/runtime/panic.go:679 +0x1b2
github.com/kabanero-io/kabanero-operator/pkg/controller/collection.(*ReconcileCollection).ensureCollectionHasOwner(0xc0007524c0, 0xc0009a45a0, 0x0, 0x2, 0x18ee2c0)
        src/github.com/kabanero-io/kabanero-operator/pkg/controller/collection/collection_controller.go:244 +0x17e
github.com/kabanero-io/kabanero-operator/pkg/controller/collection.(*ReconcileCollection).ReconcileCollection(0xc0007524c0, 0xc0009a45a0, 0x0, 0xc000c16540, 0x2, 0x2, 0x0)
        src/github.com/kabanero-io/kabanero-operator/pkg/controller/collection/collection_controller.go:297 +0x2e3
github.com/kabanero-io/kabanero-operator/pkg/controller/collection.(*ReconcileCollection).Reconcile(0xc0007524c0, 0xc0004e6cd9, 0x7, 0xc0003159e0, 0x11, 0x5, 0x348, 0xc0005be000, 0xd)
        src/github.com/kabanero-io/kabanero-operator/pkg/controller/collection/collection_controller.go:162 +0x46c
github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000a43c0, 0x0)
        src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x20a
github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
        src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005efba0)
        src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005efba0, 0x3b9aca00, 0x0, 0x1, 0xc0000861e0)
        src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0005efba0, 0x3b9aca00, 0xc0000861e0)
        src/github.com/kabanero-io/kabanero-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        src/github.com/kabanero-io/kabanero-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32e
```

**Comment by kaczyns** [comment]
@dacleyra I agree this needs to be fixed, but I'm wondering if the reason the controller got control at all was because the WATCH_NAMESPACE in the kab-operator deployment is set to `""`?

**Comment by dacleyra** [comment]
With the OLM installation, our option is currently only namespace scope install.
As such, it's not possible to re-create this under normal circumstances in 0.3.0.
Creating a Kabanero or Collection instance in another namespace is entirely ignored.

If we become a cluster scoped operator, (and update sdk/controller-runtime), we may or may not encounter this issue.
